# 这个配置是必须写死的,不能去配置,因为动态配置不合适
server:
  port: 8888

#发现服务的客户端
eureka:
  instance:
    hostname: config
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

# 配置文件存在git上
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenfromsz/spring-cloud-config-repo


  rabbitmq:
      #addresses: amqp://192.168.1.214:5672
      addresses: ${vcap.services.${PREFIX:}rabbitmq.credentials.uri:amqp://${RABBITMQ_HOST:10.224.68.72}:${RABBITMQ_PORT:5673}}
      username: guest
      password: guest

